server:
  port: 9191
spring:
  application:
    name: ribbon-only-client
PAYMENT-SERVICE:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9091,localhost:9091
    ServerListRefreshInterval: 15000